// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260130013655_MigrateToSqlServer")]
    partial class MigrateToSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Domain.ActivityAttendee", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHost")
                        .HasColumnType("bit");

                    b.HasKey("ActivityId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityAttendees");
                });

            modelBuilder.Entity("Domain.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RecipientPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Address_UserId");

                    b.HasIndex("UserId", "IsDefault")
                        .HasDatabaseName("IX_Address_UserId_IsDefault");

                    b.HasIndex("UserId", "IsDeleted")
                        .HasDatabaseName("IX_Address_UserId_IsDeleted")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Domain.AfterSalesTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRequiredEvidence")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrderItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolicyViolation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RequestedAction")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TicketStatus")
                        .HasColumnType("int");

                    b.Property<int>("TicketType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo")
                        .HasDatabaseName("IX_AfterSalesTicket_AssignedTo");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AfterSalesTicket_CreatedAt");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_AfterSalesTicket_CustomerId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_AfterSalesTicket_OrderId");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("IX_AfterSalesTicket_OrderItemId");

                    b.HasIndex("ResolvedAt")
                        .HasDatabaseName("IX_AfterSalesTicket_ResolvedAt");

                    b.HasIndex("TicketStatus")
                        .HasDatabaseName("IX_AfterSalesTicket_TicketStatus");

                    b.HasIndex("TicketType")
                        .HasDatabaseName("IX_AfterSalesTicket_TicketType");

                    b.HasIndex("CustomerId", "TicketStatus")
                        .HasDatabaseName("IX_AfterSalesTicket_CustomerId_Status");

                    b.ToTable("AfterSalesTickets", t =>
                        {
                            t.HasCheckConstraint("CK_AfterSalesTicket_TicketStatus", "[TicketStatus] IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_AfterSalesTicket_TicketType", "[TicketType] IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Domain.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Cart_CreatedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Cart_Status");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Cart_UpdatedAt");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_Cart_User_Active")
                        .HasFilter("[Status] = 1");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_Cart_UserId_Status");

                    b.ToTable("Carts", t =>
                        {
                            t.HasCheckConstraint("CK_Cart_Status", "[Status] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Domain.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId")
                        .HasDatabaseName("IX_CartItem_CartId");

                    b.HasIndex("ProductVariantId")
                        .HasDatabaseName("IX_CartItem_ProductVariantId");

                    b.HasIndex("CartId", "ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("UX_CartItem_Cart_ProductVariant");

                    b.ToTable("CartItems", t =>
                        {
                            t.HasCheckConstraint("CK_CartItem_Quantity", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("Domain.FeatureToggle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Scope")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ScopeValue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FeatureName")
                        .IsUnique()
                        .HasDatabaseName("UX_FeatureToggle_FeatureName");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("IX_FeatureToggle_IsEnabled")
                        .HasFilter("[IsEnabled] = 1");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("FeatureName", "IsEnabled")
                        .HasDatabaseName("IX_FeatureToggle_FeatureName_IsEnabled");

                    b.HasIndex("Scope", "ScopeValue")
                        .HasDatabaseName("IX_FeatureToggle_Scope_ScopeValue");

                    b.ToTable("FeatureToggles", t =>
                        {
                            t.HasCheckConstraint("CK_FeatureToggle_EffectivePeriod", "EffectiveTo IS NULL OR EffectiveTo > EffectiveFrom");

                            t.HasCheckConstraint("CK_FeatureToggle_Scope_ScopeValue", "(Scope IS NULL AND ScopeValue IS NULL)OR (Scope IS NOT NULL AND ScopeValue IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Domain.InboundRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalItems")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedAt")
                        .HasDatabaseName("IX_InboundRecord_ApprovedAt");

                    b.HasIndex("ApprovedBy")
                        .HasDatabaseName("IX_InboundRecord_ApprovedBy");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_InboundRecord_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_InboundRecord_CreatedBy");

                    b.HasIndex("SourceType")
                        .HasDatabaseName("IX_InboundRecord_SourceType");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_InboundRecord_Status");

                    b.ToTable("InboundRecords", t =>
                        {
                            t.HasCheckConstraint("CK_InboundRecord_SourceType", "[SourceType] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_InboundRecord_Status", "[Status] IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_InboundRecord_Status_ApprovedAt_RejectedAt", "(Status = 0 AND ApprovedAt IS NULL AND ApprovedBy IS NULL AND RejectedAt IS NULL AND RejectionReason IS NULL)OR (Status = 1 AND ApprovedAt IS NOT NULL AND ApprovedBy IS NOT NULL AND RejectedAt IS NULL AND RejectionReason IS NULL)OR (Status = 2 AND RejectedAt IS NOT NULL AND RejectionReason IS NOT NULL AND ApprovedAt IS NULL AND ApprovedBy IS NULL)");
                        });
                });

            modelBuilder.Entity("Domain.InboundRecordItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InboundRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InboundRecordId")
                        .HasDatabaseName("IX_InboundRecordItem_InboundRecordId");

                    b.HasIndex("ProductVariantId")
                        .HasDatabaseName("IX_InboundRecordItem_ProductVariantId");

                    b.HasIndex("InboundRecordId", "ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("UX_InboundRecordItem_Record_ProductVariant");

                    b.ToTable("InboundRecordItems", t =>
                        {
                            t.HasCheckConstraint("CK_InboundRecordItem_Quantity", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("Domain.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedAt")
                        .HasDatabaseName("IX_InventoryTransaction_ApprovedAt");

                    b.HasIndex("ApprovedBy")
                        .HasDatabaseName("IX_InventoryTransaction_ApprovedBy");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_InventoryTransaction_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_InventoryTransaction_CreatedBy");

                    b.HasIndex("ProductVariantId")
                        .HasDatabaseName("IX_InventoryTransaction_ProductVariantId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_InventoryTransaction_Status");

                    b.HasIndex("TransactionType")
                        .HasDatabaseName("IX_InventoryTransaction_TransactionType");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_InventoryTransaction_UserId");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("IX_InventoryTransaction_Reference");

                    b.ToTable("InventoryTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_InventoryTransaction_Quantity_Valid", "Quantity > 0");

                            t.HasCheckConstraint("CK_InventoryTransaction_ReferenceType", "[ReferenceType] IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_InventoryTransaction_ReferenceType_ReferenceId", "(ReferenceType IN (1,2,3) AND ReferenceId IS NOT NULL)OR (ReferenceType = 4)");

                            t.HasCheckConstraint("CK_InventoryTransaction_Status", "[Status] IN (0, 1)");

                            t.HasCheckConstraint("CK_InventoryTransaction_Status_ApprovedAt", "(Status = 0 AND ApprovedAt IS NULL AND ApprovedBy IS NULL)OR (Status = 1 AND ApprovedAt IS NOT NULL AND ApprovedBy IS NOT NULL)");

                            t.HasCheckConstraint("CK_InventoryTransaction_Type", "[TransactionType] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CancellationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBySalesStaff")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("DepositAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("OrderSource")
                        .HasColumnType("int");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<decimal?>("RemainingAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("IX_Order_AddressId");

                    b.HasIndex("CancellationDeadline")
                        .HasDatabaseName("IX_Order_CancellationDeadline");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Order_CreatedAt");

                    b.HasIndex("CreatedBySalesStaff")
                        .HasDatabaseName("IX_Order_CreatedBySalesStaff");

                    b.HasIndex("OrderSource")
                        .HasDatabaseName("IX_Order_OrderSource");

                    b.HasIndex("OrderStatus")
                        .HasDatabaseName("IX_Order_OrderStatus");

                    b.HasIndex("OrderType")
                        .HasDatabaseName("IX_Order_OrderType");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Order_UserId");

                    b.HasIndex("UserId", "OrderStatus")
                        .HasDatabaseName("IX_Order_UserId_OrderStatus");

                    b.ToTable("Orders", t =>
                        {
                            t.HasCheckConstraint("CK_Order_Amount", "[TotalAmount] >= 0 AND [ShippingFee] >= 0");

                            t.HasCheckConstraint("CK_Order_Source", "[OrderSource] IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_Order_Status", "[OrderStatus] IN (0, 1, 2, 3, 4, 5, 6, 7)");

                            t.HasCheckConstraint("CK_Order_Type", "[OrderType] IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Domain.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_OrderItem_OrderId");

                    b.HasIndex("ProductVariantId")
                        .HasDatabaseName("IX_OrderItem_ProductVariantId");

                    b.HasIndex("OrderId", "ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("UX_OrderItem_Order_ProductVariant");

                    b.ToTable("OrderItems", t =>
                        {
                            t.HasCheckConstraint("CK_OrderItem_Quantity", "Quantity > 0");

                            t.HasCheckConstraint("CK_OrderItem_UnitPrice", "UnitPrice >= 0");
                        });
                });

            modelBuilder.Entity("Domain.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_OrderStatusHistory_CreatedAt");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_OrderStatusHistory_OrderId");

                    b.HasIndex("OrderId", "CreatedAt")
                        .HasDatabaseName("IX_OrderStatusHistory_OrderId_CreatedAt");

                    b.ToTable("OrderStatusHistories");
                });

            modelBuilder.Entity("Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaymentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_Payment_OrderId");

                    b.HasIndex("PaymentAt")
                        .HasDatabaseName("IX_Payment_PaymentAt");

                    b.HasIndex("PaymentStatus")
                        .HasDatabaseName("IX_Payment_PaymentStatus");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("IX_Payment_TransactionId");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payment_Amount", "[Amount] >= 0");

                            t.HasCheckConstraint("CK_Payment_Method", "[PaymentMethod] > 0");

                            t.HasCheckConstraint("CK_Payment_Status", "[PaymentStatus] > 0");

                            t.HasCheckConstraint("CK_Payment_Status_PaymentAt", "\r\n                    (\r\n                        PaymentStatus = 1 AND PaymentAt IS NULL\r\n                    )\r\n                    OR\r\n                    (\r\n                        PaymentStatus IN (2,3,4) AND PaymentAt IS NOT NULL\r\n                    )\r\n                    ");

                            t.HasCheckConstraint("CK_Payment_Transaction_By_Method", "\r\n                    (\r\n                        PaymentMethod = 1\r\n                    )\r\n                    OR\r\n                    (\r\n                        PaymentMethod IN (2,3) AND TransactionId IS NOT NULL\r\n                    )\r\n                    ");

                            t.HasCheckConstraint("CK_Payment_Type", "[PaymentType] > 0");
                        });
                });

            modelBuilder.Entity("Domain.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Domain.PolicyConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CustomizedLensRefundable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EvidenceRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PolicyType")
                        .HasColumnType("int");

                    b.Property<bool>("RefundAllowed")
                        .HasColumnType("bit");

                    b.Property<int?>("ReturnWindowDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("WarrantyMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_PolicyConfiguration_IsActive")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("PolicyType")
                        .HasDatabaseName("IX_PolicyConfiguration_PolicyType");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("IsActive", "EffectiveFrom", "EffectiveTo")
                        .HasDatabaseName("IX_PolicyConfiguration_Active_EffectivePeriod");

                    b.HasIndex("PolicyType", "IsActive", "IsDeleted")
                        .HasDatabaseName("IX_PolicyConfiguration_Type_Active_Deleted")
                        .HasFilter("[IsActive] = 1 AND [IsDeleted] = 0");

                    b.ToTable("PolicyConfigurations", t =>
                        {
                            t.HasCheckConstraint("CK_PolicyConfiguration_EffectivePeriod", "EffectiveTo IS NULL OR (EffectiveTo > EffectiveFrom)");

                            t.HasCheckConstraint("CK_PolicyConfiguration_PolicyType", "[PolicyType] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_PolicyConfiguration_ReturnWindowDays_Requires_ReturnPolicy", "\r\n                    (PolicyType != 1 AND ReturnWindowDays IS NULL)\r\n                    OR\r\n                    (PolicyType = 1 AND ReturnWindowDays IS NOT NULL AND ReturnWindowDays >= 0)\r\n                    ");

                            t.HasCheckConstraint("CK_PolicyConfiguration_WarrantyMonths_Requires_WarrantyPolicy", "\r\n                    (PolicyType != 2 AND WarrantyMonths IS NULL)\r\n                    OR\r\n                    (PolicyType = 2 AND WarrantyMonths IS NOT NULL AND WarrantyMonths >= 0)\r\n                    ");
                        });
                });

            modelBuilder.Entity("Domain.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerificationNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("VerifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Prescription_CreatedAt");

                    b.HasIndex("IsVerified")
                        .HasDatabaseName("IX_Prescription_IsVerified");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("UX_Prescription_OrderId");

                    b.HasIndex("VerifiedAt")
                        .HasDatabaseName("IX_Prescription_VerifiedAt");

                    b.HasIndex("VerifiedBy")
                        .HasDatabaseName("IX_Prescription_VerifiedBy");

                    b.ToTable("Prescriptions", t =>
                        {
                            t.HasCheckConstraint("CK_Prescription_Verification_Consistency", "\r\n                    (IsVerified = 0 AND VerifiedAt IS NULL AND VerifiedBy IS NULL)\r\n                    OR\r\n                    (IsVerified = 1 AND VerifiedAt IS NOT NULL AND VerifiedBy IS NOT NULL)\r\n                    ");
                        });
                });

            modelBuilder.Entity("Domain.PrescriptionDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ADD")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("AXIS")
                        .HasColumnType("int");

                    b.Property<decimal?>("CYL")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Eye")
                        .HasColumnType("int");

                    b.Property<decimal?>("PD")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("SPH")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId")
                        .HasDatabaseName("IX_PrescriptionDetail_PrescriptionId");

                    b.HasIndex("PrescriptionId", "Eye")
                        .IsUnique()
                        .HasDatabaseName("UX_PrescriptionDetail_PrescriptionId_Eye");

                    b.ToTable("PrescriptionDetails", t =>
                        {
                            t.HasCheckConstraint("CK_PrescriptionDetail_AXIS", "[AXIS] IS NULL OR ([AXIS] BETWEEN 0 AND 180)");

                            t.HasCheckConstraint("CK_PrescriptionDetail_AXIS_Requires_CYL", "\r\n                    (CYL IS NULL AND AXIS IS NULL)\r\n                    OR\r\n                    (CYL IS NOT NULL AND AXIS IS NOT NULL)\r\n                    ");

                            t.HasCheckConstraint("CK_PrescriptionDetail_CYL", "[CYL] IS NULL OR ([CYL] BETWEEN -6.00 AND 0.00)");

                            t.HasCheckConstraint("CK_PrescriptionDetail_Eye", "[Eye] IN (1, 2)");

                            t.HasCheckConstraint("CK_PrescriptionDetail_PD", "[PD] IS NULL OR ([PD] BETWEEN 40.00 AND 80.00)");

                            t.HasCheckConstraint("CK_PrescriptionDetail_SPH", "[SPH] IS NULL OR ([SPH] BETWEEN -20.00 AND 20.00)");
                        });
                });

            modelBuilder.Entity("Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Brand")
                        .HasDatabaseName("IX_Product_Brand");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Product_CategoryId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Product_CreatedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Product_Status");

                    b.HasIndex("CategoryId", "Status")
                        .HasDatabaseName("IX_Product_CategoryId_Status");

                    b.ToTable("Products", t =>
                        {
                            t.HasCheckConstraint("CK_Product_Status", "[Status] IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_Product_Type", "[Type] IN (1, 2, 3, 4, 5)");
                        });
                });

            modelBuilder.Entity("Domain.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ProductCategory_IsActive")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductCategory_Slug");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Domain.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModelUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_ProductImage_IsDeleted")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_ProductImage_ProductId");

                    b.HasIndex("ProductVariantId")
                        .HasDatabaseName("IX_ProductImage_ProductVariantId");

                    b.HasIndex("ProductId", "DisplayOrder")
                        .HasDatabaseName("IX_ProductImage_ProductId_DisplayOrder");

                    b.HasIndex("ProductVariantId", "DisplayOrder")
                        .HasDatabaseName("IX_ProductImage_ProductVariantId_DisplayOrder");

                    b.ToTable("ProductImages", t =>
                        {
                            t.HasCheckConstraint("CK_ProductImage_Reference", "([ProductVariantId] IS NOT NULL AND [ProductId] IS NULL) OR ([ProductVariantId] IS NULL AND [ProductId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Domain.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BridgeWidth")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("CompareAtPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("FrameWidth")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LensWidth")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Size")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("TempleLength")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("VariantName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Color")
                        .HasDatabaseName("IX_ProductVariant_Color");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ProductVariant_IsActive")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_ProductVariant_ProductId");

                    b.HasIndex("SKU")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductVariant_SKU");

                    b.HasIndex("Size")
                        .HasDatabaseName("IX_ProductVariant_Size");

                    b.HasIndex("ProductId", "IsActive")
                        .HasDatabaseName("IX_ProductVariant_ProductId_IsActive");

                    b.ToTable("ProductVariants", t =>
                        {
                            t.HasCheckConstraint("CK_ProductVariant_CompareAtPrice", "[CompareAtPrice] IS NULL OR [CompareAtPrice] >= [Price]");

                            t.HasCheckConstraint("CK_ProductVariant_Price", "[Price] >= 0");
                        });
                });

            modelBuilder.Entity("Domain.PromoUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscountApplied")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_PromoUsageLog_OrderId");

                    b.HasIndex("PromotionId")
                        .HasDatabaseName("IX_PromoUsageLog_PromotionId");

                    b.HasIndex("UsedAt")
                        .HasDatabaseName("IX_PromoUsageLog_UsedAt");

                    b.HasIndex("OrderId", "PromotionId")
                        .IsUnique()
                        .HasDatabaseName("UX_PromoUsageLog_Order_Promotion");

                    b.ToTable("PromoUsageLogs", t =>
                        {
                            t.HasCheckConstraint("CK_PromoUsageLog_DiscountApplied", "DiscountApplied >= 0");
                        });
                });

            modelBuilder.Entity("Domain.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxDiscountValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PromoCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PromoName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PromotionType")
                        .HasColumnType("int");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int?>("UsageLimitPerCustomer")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PromoCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Promotion_PromoCode");

                    b.HasIndex("PromotionType")
                        .HasDatabaseName("IX_Promotion_PromotionType");

                    b.HasIndex("ValidFrom", "ValidTo")
                        .HasDatabaseName("IX_Promotion_ValidDates");

                    b.HasIndex("IsActive", "ValidFrom", "ValidTo")
                        .HasDatabaseName("IX_Promotion_Active_ValidPeriod");

                    b.HasIndex("PromotionType", "ValidFrom", "ValidTo")
                        .HasDatabaseName("IX_Promotion_Type_ValidPeriod");

                    b.ToTable("Promotions", t =>
                        {
                            t.HasCheckConstraint("CK_Promotion_DiscountValue", "DiscountValue >= 0");

                            t.HasCheckConstraint("CK_Promotion_DiscountValue_ByType", "\r\n                    (PromotionType = 0 AND DiscountValue > 0 AND DiscountValue <= 100)\r\n                    OR (PromotionType = 1 AND DiscountValue > 0)\r\n                    OR (PromotionType = 2 AND DiscountValue = 0)\r\n                    ");

                            t.HasCheckConstraint("CK_Promotion_MaxDiscountValue", "MaxDiscountValue IS NULL OR MaxDiscountValue >= 0");

                            t.HasCheckConstraint("CK_Promotion_Type", "[PromotionType] IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_Promotion_ValidPeriod", "ValidTo > ValidFrom");
                        });
                });

            modelBuilder.Entity("Domain.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RefundAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefundReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RefundStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("IX_Refund_PaymentId");

                    b.HasIndex("RefundAt")
                        .HasDatabaseName("IX_Refund_RefundAt");

                    b.HasIndex("RefundStatus")
                        .HasDatabaseName("IX_Refund_RefundStatus");

                    b.ToTable("Refunds", t =>
                        {
                            t.HasCheckConstraint("CK_Refund_Amount", "[Amount] >= 0");

                            t.HasCheckConstraint("CK_Refund_Status", "[RefundStatus] IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("Domain.ShipmentInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualDeliveryAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CarrierName")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EstimatedDeliveryAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PackageDimensions")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PackageWeight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrackingCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrackingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActualDeliveryAt")
                        .HasDatabaseName("IX_ShipmentInfo_DeliveredAt");

                    b.HasIndex("CarrierName")
                        .HasDatabaseName("IX_ShipmentInfo_CarrierName");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_ShipmentInfo_CreatedBy");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("UX_ShipmentInfo_OrderId");

                    b.HasIndex("ShippedAt")
                        .HasDatabaseName("IX_ShipmentInfo_ShippedAt");

                    b.HasIndex("TrackingCode")
                        .HasDatabaseName("IX_ShipmentInfo_TrackingCode");

                    b.ToTable("ShipmentInfos", t =>
                        {
                            t.HasCheckConstraint("CK_ShipmentInfo_Carrier", "[CarrierName] IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("Domain.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityAvailable")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("[QuantityOnHand] - [QuantityReserved]", true);

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<int>("QuantityReserved")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("IX_Stock_ProductVariantId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Stock_UpdatedAt");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("IX_Stock_UpdatedBy");

                    b.ToTable("Stocks", t =>
                        {
                            t.HasCheckConstraint("CK_Stock_Quantity_Valid", "[QuantityOnHand] >= 0 AND [QuantityReserved] >= 0 AND [QuantityReserved] <= [QuantityOnHand]");
                        });
                });

            modelBuilder.Entity("Domain.TicketAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_TicketAttachment_CreatedAt");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_TicketAttachment_DeletedAt");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("IX_TicketAttachment_DeletedBy");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_TicketAttachment_TicketId");

                    b.HasIndex("TicketId", "DeletedAt")
                        .HasDatabaseName("IX_TicketAttachment_TicketId_DeletedAt")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("TicketAttachments", t =>
                        {
                            t.HasCheckConstraint("CK_TicketAttachment_Deletion_Consistency", "\r\n                    (DeletedAt IS NULL AND DeletedBy IS NULL)\r\n                    OR\r\n                    (DeletedAt IS NOT NULL AND DeletedBy IS NOT NULL)\r\n                    ");
                        });
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.ActivityAttendee", b =>
                {
                    b.HasOne("Domain.Activity", "Activity")
                        .WithMany("Attendees")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Address", b =>
                {
                    b.HasOne("Domain.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.AfterSalesTicket", b =>
                {
                    b.HasOne("Domain.User", "AssignedStaff")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Order", "Order")
                        .WithMany("AfterSalesTickets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.OrderItem", "OrderItem")
                        .WithMany("AfterSalesTickets")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AssignedStaff");

                    b.Navigation("Customer");

                    b.Navigation("Order");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("Domain.Cart", b =>
                {
                    b.HasOne("Domain.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.CartItem", b =>
                {
                    b.HasOne("Domain.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Domain.FeatureToggle", b =>
                {
                    b.HasOne("Domain.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("Domain.InboundRecord", b =>
                {
                    b.HasOne("Domain.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Approver");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Domain.InboundRecordItem", b =>
                {
                    b.HasOne("Domain.InboundRecord", "InboundRecord")
                        .WithMany("Items")
                        .HasForeignKey("InboundRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InboundRecord");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Domain.InventoryTransaction", b =>
                {
                    b.HasOne("Domain.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Creator");

                    b.Navigation("ProductVariant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Order", b =>
                {
                    b.HasOne("Domain.Address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "SalesStaff")
                        .WithMany()
                        .HasForeignKey("CreatedBySalesStaff")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Address");

                    b.Navigation("SalesStaff");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.OrderItem", b =>
                {
                    b.HasOne("Domain.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Domain.OrderStatusHistory", b =>
                {
                    b.HasOne("Domain.Order", "Order")
                        .WithMany("StatusHistories")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Domain.Payment", b =>
                {
                    b.HasOne("Domain.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Domain.Photo", b =>
                {
                    b.HasOne("Domain.User", "User")
                        .WithMany("Photos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.PolicyConfiguration", b =>
                {
                    b.HasOne("Domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.User", "Deleter")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("Deleter");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("Domain.Prescription", b =>
                {
                    b.HasOne("Domain.Order", "Order")
                        .WithOne("Prescription")
                        .HasForeignKey("Domain.Prescription", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "Verifier")
                        .WithMany()
                        .HasForeignKey("VerifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");

                    b.Navigation("Verifier");
                });

            modelBuilder.Entity("Domain.PrescriptionDetail", b =>
                {
                    b.HasOne("Domain.Prescription", "Prescription")
                        .WithMany("Details")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Domain.Product", b =>
                {
                    b.HasOne("Domain.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.ProductImage", b =>
                {
                    b.HasOne("Domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.User", "Deleter")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.ProductVariant", "ProductVariant")
                        .WithMany("Images")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Creator");

                    b.Navigation("Deleter");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Domain.ProductVariant", b =>
                {
                    b.HasOne("Domain.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.PromoUsageLog", b =>
                {
                    b.HasOne("Domain.Order", "Order")
                        .WithMany("PromoUsageLogs")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Promotion", "Promotion")
                        .WithMany("UsageLogs")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Domain.Refund", b =>
                {
                    b.HasOne("Domain.Payment", "Payment")
                        .WithMany("Refunds")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Domain.ShipmentInfo", b =>
                {
                    b.HasOne("Domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Order", "Order")
                        .WithOne("ShipmentInfo")
                        .HasForeignKey("Domain.ShipmentInfo", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Domain.Stock", b =>
                {
                    b.HasOne("Domain.ProductVariant", "ProductVariant")
                        .WithOne("Stock")
                        .HasForeignKey("Domain.Stock", "ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProductVariant");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Domain.TicketAttachment", b =>
                {
                    b.HasOne("Domain.User", "Deleter")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.AfterSalesTicket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deleter");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("Domain.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Domain.AfterSalesTicket", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Domain.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domain.InboundRecord", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domain.Order", b =>
                {
                    b.Navigation("AfterSalesTickets");

                    b.Navigation("OrderItems");

                    b.Navigation("Payments");

                    b.Navigation("Prescription");

                    b.Navigation("PromoUsageLogs");

                    b.Navigation("ShipmentInfo");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("Domain.OrderItem", b =>
                {
                    b.Navigation("AfterSalesTickets");
                });

            modelBuilder.Entity("Domain.Payment", b =>
                {
                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("Domain.Prescription", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Domain.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Domain.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.ProductVariant", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Domain.Promotion", b =>
                {
                    b.Navigation("UsageLogs");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Addresses");

                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
